name: "sonar-quality-gate"
description: "This plugin will be intergate to CI/CD, get quality code of sonarqube and push report to merge request when has change."
branding:
  icon: "award"
  color: "green"
inputs:
  login:
    description: "The authentication token or login of a SonarQube user with Execute Analysis permission on the project."
    required: true
  skipScanner:
    description: "skip scanner"
    required: false
  analysisArgs:
    description: "Sonar scanner arguments"
    required: false
  docker_username:
    description: "Docker username"
    required: true
  docker_password:
    description: "Docker password"
    required: true

outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "composite"
  steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker_username }}
        password: ${{ inputs.docker_password }}

    - name: Run Sonar Quality Gate
      shell: bash
      run: |
        docker run --rm \
          -e SONAR_TOKEN=${{ inputs.login }} \
          upfluence/sonar-quality-gate-action:0.0.1 \
          ${{ inputs.analysisArgs }}
